

INSERT INTO categories (name) VALUES
    ('suculentas'),
    ('cactos'),
    ('samambaias'),
    ('flores'),
    ('jardinagem');

INSERT INTO products (title, price, description, image, category_id) VALUES
    ('Sempre Vivas', 10.0, 'Essa é uma suculenta naturalmente colorida que chega a ficar com um vermelho bem forte.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/cacto_suculenta_011.jpg', 1),
    ('Coroa de frade', 12.0, 'O apelido deve-se à sua estrutura: corpo circular espinhento, com uma coroa colorida no topo. Popularmente, entendeu-se similaridade entre sua forma e um solidéu eclesiástico.', 'https://www.orquidario4e.com.br/Content/images/product/01109111193_1_m_d_00.jpg', 2),
    ('Samambaia Americana', 20.0, 'É um dos tipos mais exuberantes de samambaias. Isso porque, as folhas da planta formam grandes e finos pendentes, de uma cor verde clara. O visual é um pouco “selvagem”, com as folhas crescendo para diversos lados.', 'https://static3.tcdn.com.br/img/img_prod/350075/samambaia_americana_8677_1_20190521161357.jpg', 3),
    ('Mini-margarida', 23.0, 'Ela é uma ótima opção para decorar qualquer ambiente de casa, contanto que haja incidência solar direta, durante o dia inteiro. Contudo, também é possível cultivá-la em locais à meia sombra.', 'https://www.ecompletocdn.com.br/i/fp/1606/1074603_2_1564080630.jpg', 4),
    ('Kit jardinagem', 45.0, 'kit com as principais ferramentas para cuidar das suas plantas.', 'https://www.dutramaquinas.com.br/view/img/produtos/alta/59370_conjunto_para_jardim_4_pecas.jpg', 5),
    ('Principe Negro', 6.0, 'É uma suculenta com folhagem bem escura, quase preta. No inverno, ela assume um vermelho bem escuro.', 'https://i.pinimg.com/564x/1c/9e/9a/1c9e9ac78e09c74d09fbeb71dc73cf82.jpg', 1),
    ('Echeveria Pintada', 4.0, 'Essa planta parece até uma pintura. Ela desenvolve uma folhagem côncava com traços vermelhos marcantes.', 'https://st2.depositphotos.com/4640111/i/600/depositphotos_444179912-stock-photo-green-house-plants-potted-succulent.jpg', 1),
    ('Colar de pérolas', 12.0, 'Como o próprio nome indica, as suculentas pendentes nomes colar de pérolas são tão delicadas quanto a pedra preciosa.', 'https://static3.tcdn.com.br/img/img_prod/350075/suculenta_colar_de_perolas_artificial_verde_5h_37cm_12443_1_20200326152426.jpg', 1),
    ('Planta Jade', 5.0, 'Com folhas que podem ficar vermelhas se expostas à luz solar prolongada, as Crassula Ovatas são suculentas versáteis, que prosperam tanto em ambientes internos quanto externos.', 'https://www.noticiasdejardim.com/wp-content/uploads/2021/06/416QSdBY8-L._SL500_.jpg', 1),
    ('Arbusto Elefante', 16.0, 'O porte lembra um pouco o da planta jade, no entanto, suas folhas são menores, mais delicadas. Também possui o aspecto de arvoreta, lembrando um bonsai. É uma planta coringa, que se adaptaa a diferentes ambientes de cultivo, por isso, a baixa luminosidade não fará mal a ela.', 'https://http2.mlstatic.com/D_NQ_NP_893415-MPE43966282557_112020-O.jpg', 1),
    ('Cacto ouriço', 4.0, 'Floresce no verão e deve-se cultivar em Sol pleno.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/cacto_003.jpg', 2),
    ('Capuz de monge', 12.0, 'Planta cilíndrica que deve ser cultivada em Sol pleno.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/cacto_001.jpg', 2),
    ('Orelha Mickey', 12.0, 'Esse cacto pode chegar até 15 cm de comprimento. Os espinhos são pequenos e fáceis de quebrar. Ele ainda pode gerar flores de cor amarelas cremosas de 5 cm de largura no verão, que posteriormente podem formar frutos roxos globulares.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/cacto_suculenta_010.jpg', 2),
    ('Rabo de rato', 20.0, 'Apresenta ramos inicialmente eretos, que posteriormente se tornam prostrados ou pendentes. Eles são verdes e cilíndricos, com diâmetro de 2 a 3 cm, recobertos de espinhos de cor cinza claro a acastanhados, que em combinação com o caule, conferem à ramagem um tom cinza azulado ou marrom claro.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/cacto_suculenta_001.jpg', 2),
    ('A almofada de alfinetes', 4.0, 'O mammillaria decipiens brota em diferentes braços arredondados, de baixa altura. Eles são protegidos por uma verdadeira armadura de espinhos.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/cacto_002.jpg', 2),
    ('Samambaia Argentina', 13.0, 'Visualmente, a Samambaia Argentina é muito parecida com a Americana. Porém, ela tem folhas mais ralas, “crespas” e mais longas.', 'https://faroeflora.com.br/wp-content/uploads/2019/11/samambaia-argentina-compacta.jpg', 3),
    ('Samambaia Amazonas', 12.0, 'A Samambaia Amazonas tem folhas largas e de um verde mais intenso. Ela não possui o visual “clássico” das samambaias, de folhas finas, pendentes e com pequenas bolinhas em sua superfície. Mas vale dizer que ela também é do tipo pendente. Então, pode ser uma boa opção plantá-la em locais altos, para que suas folhas criem um belo visual.', 'https://cdn.awsli.com.br/800x800/935/935548/produto/35540201/87a86153bd.jpg', 3),
    ('Chifre-de-veado', 26.0, 'Como seu nome sugere, suas folhas lembram os chifres desse animal. Por isso, são mais largas e espaçadas. Também têm algumas “ramificações”, que criam o visual dos chifres.', 'https://cdn.awsli.com.br/800x800/935/935548/produto/35539789/254c5fec30.jpg', 3),
    ('Samambaia Renda Francesa', 15.0, 'As folhas da Renda Francesa são menores e mais delicadas, têm um visual mais “fofo” e bonito para o centro de mesas e pequenos vasos.', 'https://static.cloud-boxloja.com/lojas/9s0e9/produtos/a84b53f3-4501-4cee-b855-ca7e2c598ef8.jpg', 3),
    ('Samambaia Avenca', 20.0, 'A Avenca é um tipo de samambaia que pode atingir até 70 cm de altura. Mas suas folhas são bem diferentes das demais. Em vez de finas e esticadas, as folhas dessa planta são quase que redondas. Outra característica importante da planta é que suas folhas são da cor verde clara. Então, a espécie ganha um aspecto ainda mais delicado, leve.', 'https://cactosesuculentas.com/wp-content/uploads/2020/01/Avenca-700x614.jpg', 3),
    ('Amaryllis', 21.0, 'Por ser uma planta tropical, o indicado é que a flor amarílis receba iluminação natural por, pelo menos, 6 horas por dia. Ela precisa disso para seu desenvolvimento. Evite deixar a flor amarílis na sombra. Coloque o vaso numa janela iluminada, na varanda de vidro ou no jardim.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/amaryllis_001.jpg', 4),
    ('Hortência', 15.0, 'É uma planta arbustiva, nativa da Ásia, que pode chegar a 1,5 metro de altura. A planta deve ser regada com muita frequência, principalmente em climas secos, nesse caso, a rega é diária. Apesar de precisar de luminosidade, não pode ser direta, então o ideal é deixar em um local à meia sombra.', 'https://abcgarden.fbitsstatic.net/img/p/hortencia-rosa-pote-14-201315/388469.jpg', 4),
    ('Violeta', 10.0, 'Famoso tipo de flor para vaso, a violeta é uma planta pequena com flores coloridas, queridinha nos lares. Ela precisa de luz indireta do sol e regas constantes, mas não molhe as flores, apenas o solo, pois elas apodrecem.', 'https://a-static.mlcdn.com.br/618x463/violeta-com-vaso-toque-veludo-roxa-flores-e-cia/floresecia/11856044165/e2e3ca3634e046e2de968cc6517427b3.jpg', 4),
    ('Antúrio', 25.0, 'Essa planta é nativa de território tropical, então o clima úmido e quente é ideal para o cultivo dela. Apesar disso, não pode ficar sob a luz do sol direta, e as regas devem ser frequentes (ainda maior nos meses de verão). Para uma aparência mais vistosa, borrife água também na folha. ', 'https://cdn.leroymerlin.com.br/products/_anturio_pote_17_89203814_0001_600x600.jpg', 4),
    ('Dahlia Pinnata', 11.0, 'A dália é uma planta herbácea e florífera, que sofreu grande melhoramento e muitos cruzamentos, possibilitando a disponibilização de um grande número de variedades, com portes diferentes, e principalmente com capítulos florais de cores e formas muito variadas, simples ou dobrados. Suas folhas são compostas e podem se verdes ou arroxeadas.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/dahlia_pinnata_02-600x600.jpg', 4),
    ('Adubo', 35.0, 'Adubo para cactos e suculentas.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/calcario_agricola-600x600.jpg', 5),
    ('Pulverizador', 20.0, 'pulverizador para plantas.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/guarany_multispray_500ml-600x600.jpg', 5),
    ('Jardineira', 25.0, 'Vaso estilo jardineira feito de fibra de coco. ', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/jardineira_fibra-600x600.jpg', 5),
    ('Vaso', 15.0, 'Vaso de fibra de coco compatível com diversas plantas. ', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/vaso_fibra_cuia_kit-600x600.jpg', 5),
    ('Regador', 15.0, 'Regador de plantas na cor verde.', 'https://www.chacaratropical.com.br/2020/wp-content/uploads/okla_regador_001-600x600.jpg', 5);

